/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as InqabaRouteImport } from './routes/inqaba'
import { Route as IdwRouteImport } from './routes/idw'
import { Route as IcdaRouteImport } from './routes/icda'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdwIndexRouteImport } from './routes/idw.index'
import { Route as IdwDashboardRouteImport } from './routes/idw.dashboard'
import { Route as IdwAuthRouteImport } from './routes/idw.auth'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const InqabaRoute = InqabaRouteImport.update({
  id: '/inqaba',
  path: '/inqaba',
  getParentRoute: () => rootRouteImport,
} as any)
const IdwRoute = IdwRouteImport.update({
  id: '/idw',
  path: '/idw',
  getParentRoute: () => rootRouteImport,
} as any)
const IcdaRoute = IcdaRouteImport.update({
  id: '/icda',
  path: '/icda',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdwIndexRoute = IdwIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdwRoute,
} as any)
const IdwDashboardRoute = IdwDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => IdwRoute,
} as any)
const IdwAuthRoute = IdwAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => IdwRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/icda': typeof IcdaRoute
  '/idw': typeof IdwRouteWithChildren
  '/inqaba': typeof InqabaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/idw/auth': typeof IdwAuthRoute
  '/idw/dashboard': typeof IdwDashboardRoute
  '/idw/': typeof IdwIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/icda': typeof IcdaRoute
  '/inqaba': typeof InqabaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/idw/auth': typeof IdwAuthRoute
  '/idw/dashboard': typeof IdwDashboardRoute
  '/idw': typeof IdwIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/icda': typeof IcdaRoute
  '/idw': typeof IdwRouteWithChildren
  '/inqaba': typeof InqabaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/idw/auth': typeof IdwAuthRoute
  '/idw/dashboard': typeof IdwDashboardRoute
  '/idw/': typeof IdwIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/icda'
    | '/idw'
    | '/inqaba'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/orders'
    | '/admin/products'
    | '/idw/auth'
    | '/idw/dashboard'
    | '/idw/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/icda'
    | '/inqaba'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/orders'
    | '/admin/products'
    | '/idw/auth'
    | '/idw/dashboard'
    | '/idw'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/events'
    | '/icda'
    | '/idw'
    | '/inqaba'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/orders'
    | '/admin/products'
    | '/idw/auth'
    | '/idw/dashboard'
    | '/idw/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  IcdaRoute: typeof IcdaRoute
  IdwRoute: typeof IdwRouteWithChildren
  InqabaRoute: typeof InqabaRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inqaba': {
      id: '/inqaba'
      path: '/inqaba'
      fullPath: '/inqaba'
      preLoaderRoute: typeof InqabaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idw': {
      id: '/idw'
      path: '/idw'
      fullPath: '/idw'
      preLoaderRoute: typeof IdwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icda': {
      id: '/icda'
      path: '/icda'
      fullPath: '/icda'
      preLoaderRoute: typeof IcdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idw/': {
      id: '/idw/'
      path: '/'
      fullPath: '/idw/'
      preLoaderRoute: typeof IdwIndexRouteImport
      parentRoute: typeof IdwRoute
    }
    '/idw/dashboard': {
      id: '/idw/dashboard'
      path: '/dashboard'
      fullPath: '/idw/dashboard'
      preLoaderRoute: typeof IdwDashboardRouteImport
      parentRoute: typeof IdwRoute
    }
    '/idw/auth': {
      id: '/idw/auth'
      path: '/auth'
      fullPath: '/idw/auth'
      preLoaderRoute: typeof IdwAuthRouteImport
      parentRoute: typeof IdwRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IdwRouteChildren {
  IdwAuthRoute: typeof IdwAuthRoute
  IdwDashboardRoute: typeof IdwDashboardRoute
  IdwIndexRoute: typeof IdwIndexRoute
}

const IdwRouteChildren: IdwRouteChildren = {
  IdwAuthRoute: IdwAuthRoute,
  IdwDashboardRoute: IdwDashboardRoute,
  IdwIndexRoute: IdwIndexRoute,
}

const IdwRouteWithChildren = IdwRoute._addFileChildren(IdwRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  IcdaRoute: IcdaRoute,
  IdwRoute: IdwRouteWithChildren,
  InqabaRoute: InqabaRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
